
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'PageHeader': typeof import("../components/global/PageHeader.vue")['default']
    'SiteHeader': typeof import("../components/global/SiteHeader.vue")['default']
    'WizarParametrageProfileInformationPersonnelle': typeof import("../components/WizarParametrageProfile/InformationPersonnelle.vue")['default']
    'WizarParametrageProfileInformationProfessionnelle': typeof import("../components/WizarParametrageProfile/InformationProfessionnelle.vue")['default']
    'AccountForgotPassword': typeof import("../components/account/ForgotPassword.vue")['default']
    'AccountLogin': typeof import("../components/account/Login.vue")['default']
    'AccountOtp': typeof import("../components/account/Otp.vue")['default']
    'AccountRegister': typeof import("../components/account/Register.vue")['default']
    'AccountResetPassword': typeof import("../components/account/ResetPassword.vue")['default']
    'Agenda': typeof import("../components/agenda/Agenda.vue")['default']
    'AgendaLocales': typeof import("../components/agenda/Locales")['default']
    'AgendaUtils': typeof import("../components/agenda/utils")['default']
    'AuthLockScreen': typeof import("../components/auth/LockScreen/index.vue")['default']
    'AuthLogin': typeof import("../components/auth/login/index.vue")['default']
    'AuthRecoverPassword': typeof import("../components/auth/recoverPassword/index.vue")['default']
    'AuthRegister': typeof import("../components/auth/register/index.vue")['default']
    'CommonCountToComponent': typeof import("../components/common/CountToComponent.vue")['default']
    'CommonRadioGroup': typeof import("../components/common/RadioGroup.vue")['default']
    'DashboardDashBoard': typeof import("../components/dashboard/DashBoard.vue")['default']
    'DashboardVisiteur': typeof import("../components/dashboard/Visiteur.vue")['default']
    'DashboardCommonDiagramme': typeof import("../components/dashboard/common/Diagramme.vue")['default']
    'DashboardCommonHistogramme': typeof import("../components/dashboard/common/Histogramme.vue")['default']
    'DashboardCommonStat': typeof import("../components/dashboard/common/Stat.vue")['default']
    'DashboardCommonTableauDeBord': typeof import("../components/dashboard/common/TableauDeBord.vue")['default']
    'DashboardCommonTendanceVisite': typeof import("../components/dashboard/common/TendanceVisite.vue")['default']
    'DashboardCommonData': typeof import("../components/dashboard/common/data")['default']
    'DashboardNotification': typeof import("../components/dashboard/notification.vue")['default']
    'DetailVisiteur': typeof import("../components/detail/Visiteur.vue")['default']
    'FormsAjouterProfil': typeof import("../components/forms/AjouterProfil.vue")['default']
    'FormsFormAgence': typeof import("../components/forms/FormAgence.vue")['default']
    'FormsFormCategorie': typeof import("../components/forms/FormCategorie.vue")['default']
    'FormsFormDepartement': typeof import("../components/forms/FormDepartement.vue")['default']
    'FormsFormMenu': typeof import("../components/forms/FormMenu.vue")['default']
    'FormsFormProfil': typeof import("../components/forms/FormProfil.vue")['default']
    'FormsFormService': typeof import("../components/forms/FormService.vue")['default']
    'FormsFormUser': typeof import("../components/forms/FormUser.vue")['default']
    'FormsNewPassword': typeof import("../components/forms/NewPassword.vue")['default']
    'FormsParametrageProfile': typeof import("../components/forms/ParametrageProfile.vue")['default']
    'FormsProfile': typeof import("../components/forms/Profile.vue")['default']
    'LayoutsCommonAppList': typeof import("../components/layouts/common/AppList.vue")['default']
    'LayoutsCommonAppSearch': typeof import("../components/layouts/common/AppSearch.vue")['default']
    'LayoutsCommonFooter': typeof import("../components/layouts/common/Footer.vue")['default']
    'LayoutsCommonHeaderLogo': typeof import("../components/layouts/common/HeaderLogo.vue")['default']
    'LayoutsCommonLanguageDropdown': typeof import("../components/layouts/common/LanguageDropdown.vue")['default']
    'LayoutsCommonMobileAppSearch': typeof import("../components/layouts/common/MobileAppSearch.vue")['default']
    'LayoutsCommonNotifications': typeof import("../components/layouts/common/Notifications.vue")['default']
    'LayoutsCommonParametre': typeof import("../components/layouts/common/Parametre.vue")['default']
    'LayoutsCommonParametreDropdown': typeof import("../components/layouts/common/ParametreDropdown.vue")['default']
    'LayoutsCommonProfile': typeof import("../components/layouts/common/Profile.vue")['default']
    'LayoutsCommonRightSideBar': typeof import("../components/layouts/common/RightSideBar.vue")['default']
    'LayoutsCommonSideBar': typeof import("../components/layouts/common/SideBar.vue")['default']
    'LayoutsCommonModalsModalDetail': typeof import("../components/layouts/common/modals/modalDetail.vue")['default']
    'LayoutsCommonStatStatatistique': typeof import("../components/layouts/common/stat/Statatistique.vue")['default']
    'LayoutsUtilsMenu': typeof import("../components/layouts/utils/menu")['default']
    'LayoutsUtilsRightSideBar': typeof import("../components/layouts/utils/rightSideBar")['default']
    'LayoutsUtilsTopBar': typeof import("../components/layouts/utils/topBar")['default']
    'LayoutsVerticalTopBar': typeof import("../components/layouts/vertical/TopBar.vue")['default']
    'LayoutsVerticalTopBarQrCode': typeof import("../components/layouts/vertical/TopBarQrCode.vue")['default']
    'LayoutsVertical': typeof import("../components/layouts/vertical/index.vue")['default']
    'ParametresAgence': typeof import("../components/parametres/Agence.vue")['default']
    'ParametresCategorie': typeof import("../components/parametres/Categorie.vue")['default']
    'ParametresDepartement': typeof import("../components/parametres/Departement.vue")['default']
    'ParametresMenu': typeof import("../components/parametres/Menu.vue")['default']
    'ParametresProfil': typeof import("../components/parametres/Profil.vue")['default']
    'ParametresService': typeof import("../components/parametres/Service.vue")['default']
    'ParametresUtilisateur': typeof import("../components/parametres/Utilisateur.vue")['default']
    'ParametresParametre': typeof import("../components/parametres/parametre.vue")['default']
    'ParametresUseData': typeof import("../components/parametres/useData")['default']
    'TableauDetail': typeof import("../components/tableau/Detail.vue")['default']
    'Tableau': typeof import("../components/tableau/index.vue")['default']
    'TableauT': typeof import("../components/tableau/t.vue")['default']
    'TableauUtils': typeof import("../components/tableau/utils")['default']
    'UtilityComingSoon': typeof import("../components/utility/comingSoon/index.vue")['default']
    'UtilityMaintenance': typeof import("../components/utility/maintenance/index.vue")['default']
    'Visiteur': typeof import("../components/visiteur/index.vue")['default']
    'VueWebCam': typeof import("../components/vue-web-cam.vue")['default']
    'ContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'ContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'ContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'ContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'ContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'ContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'ContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'DocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'DocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'Markdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'ProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'ProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'ProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'ProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'ProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'ProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'ProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'ProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'ProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'ProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'ProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'ProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'ProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'ProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'ProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'ProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'ProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'ProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'ProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'ProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'ProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'ProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'ProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'ProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'ProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'ProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'MDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'MDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'MDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyPageHeader': typeof import("../components/global/PageHeader.vue")['default']
    'LazySiteHeader': typeof import("../components/global/SiteHeader.vue")['default']
    'LazyWizarParametrageProfileInformationPersonnelle': typeof import("../components/WizarParametrageProfile/InformationPersonnelle.vue")['default']
    'LazyWizarParametrageProfileInformationProfessionnelle': typeof import("../components/WizarParametrageProfile/InformationProfessionnelle.vue")['default']
    'LazyAccountForgotPassword': typeof import("../components/account/ForgotPassword.vue")['default']
    'LazyAccountLogin': typeof import("../components/account/Login.vue")['default']
    'LazyAccountOtp': typeof import("../components/account/Otp.vue")['default']
    'LazyAccountRegister': typeof import("../components/account/Register.vue")['default']
    'LazyAccountResetPassword': typeof import("../components/account/ResetPassword.vue")['default']
    'LazyAgenda': typeof import("../components/agenda/Agenda.vue")['default']
    'LazyAgendaLocales': typeof import("../components/agenda/Locales")['default']
    'LazyAgendaUtils': typeof import("../components/agenda/utils")['default']
    'LazyAuthLockScreen': typeof import("../components/auth/LockScreen/index.vue")['default']
    'LazyAuthLogin': typeof import("../components/auth/login/index.vue")['default']
    'LazyAuthRecoverPassword': typeof import("../components/auth/recoverPassword/index.vue")['default']
    'LazyAuthRegister': typeof import("../components/auth/register/index.vue")['default']
    'LazyCommonCountToComponent': typeof import("../components/common/CountToComponent.vue")['default']
    'LazyCommonRadioGroup': typeof import("../components/common/RadioGroup.vue")['default']
    'LazyDashboardDashBoard': typeof import("../components/dashboard/DashBoard.vue")['default']
    'LazyDashboardVisiteur': typeof import("../components/dashboard/Visiteur.vue")['default']
    'LazyDashboardCommonDiagramme': typeof import("../components/dashboard/common/Diagramme.vue")['default']
    'LazyDashboardCommonHistogramme': typeof import("../components/dashboard/common/Histogramme.vue")['default']
    'LazyDashboardCommonStat': typeof import("../components/dashboard/common/Stat.vue")['default']
    'LazyDashboardCommonTableauDeBord': typeof import("../components/dashboard/common/TableauDeBord.vue")['default']
    'LazyDashboardCommonTendanceVisite': typeof import("../components/dashboard/common/TendanceVisite.vue")['default']
    'LazyDashboardCommonData': typeof import("../components/dashboard/common/data")['default']
    'LazyDashboardNotification': typeof import("../components/dashboard/notification.vue")['default']
    'LazyDetailVisiteur': typeof import("../components/detail/Visiteur.vue")['default']
    'LazyFormsAjouterProfil': typeof import("../components/forms/AjouterProfil.vue")['default']
    'LazyFormsFormAgence': typeof import("../components/forms/FormAgence.vue")['default']
    'LazyFormsFormCategorie': typeof import("../components/forms/FormCategorie.vue")['default']
    'LazyFormsFormDepartement': typeof import("../components/forms/FormDepartement.vue")['default']
    'LazyFormsFormMenu': typeof import("../components/forms/FormMenu.vue")['default']
    'LazyFormsFormProfil': typeof import("../components/forms/FormProfil.vue")['default']
    'LazyFormsFormService': typeof import("../components/forms/FormService.vue")['default']
    'LazyFormsFormUser': typeof import("../components/forms/FormUser.vue")['default']
    'LazyFormsNewPassword': typeof import("../components/forms/NewPassword.vue")['default']
    'LazyFormsParametrageProfile': typeof import("../components/forms/ParametrageProfile.vue")['default']
    'LazyFormsProfile': typeof import("../components/forms/Profile.vue")['default']
    'LazyLayoutsCommonAppList': typeof import("../components/layouts/common/AppList.vue")['default']
    'LazyLayoutsCommonAppSearch': typeof import("../components/layouts/common/AppSearch.vue")['default']
    'LazyLayoutsCommonFooter': typeof import("../components/layouts/common/Footer.vue")['default']
    'LazyLayoutsCommonHeaderLogo': typeof import("../components/layouts/common/HeaderLogo.vue")['default']
    'LazyLayoutsCommonLanguageDropdown': typeof import("../components/layouts/common/LanguageDropdown.vue")['default']
    'LazyLayoutsCommonMobileAppSearch': typeof import("../components/layouts/common/MobileAppSearch.vue")['default']
    'LazyLayoutsCommonNotifications': typeof import("../components/layouts/common/Notifications.vue")['default']
    'LazyLayoutsCommonParametre': typeof import("../components/layouts/common/Parametre.vue")['default']
    'LazyLayoutsCommonParametreDropdown': typeof import("../components/layouts/common/ParametreDropdown.vue")['default']
    'LazyLayoutsCommonProfile': typeof import("../components/layouts/common/Profile.vue")['default']
    'LazyLayoutsCommonRightSideBar': typeof import("../components/layouts/common/RightSideBar.vue")['default']
    'LazyLayoutsCommonSideBar': typeof import("../components/layouts/common/SideBar.vue")['default']
    'LazyLayoutsCommonModalsModalDetail': typeof import("../components/layouts/common/modals/modalDetail.vue")['default']
    'LazyLayoutsCommonStatStatatistique': typeof import("../components/layouts/common/stat/Statatistique.vue")['default']
    'LazyLayoutsUtilsMenu': typeof import("../components/layouts/utils/menu")['default']
    'LazyLayoutsUtilsRightSideBar': typeof import("../components/layouts/utils/rightSideBar")['default']
    'LazyLayoutsUtilsTopBar': typeof import("../components/layouts/utils/topBar")['default']
    'LazyLayoutsVerticalTopBar': typeof import("../components/layouts/vertical/TopBar.vue")['default']
    'LazyLayoutsVerticalTopBarQrCode': typeof import("../components/layouts/vertical/TopBarQrCode.vue")['default']
    'LazyLayoutsVertical': typeof import("../components/layouts/vertical/index.vue")['default']
    'LazyParametresAgence': typeof import("../components/parametres/Agence.vue")['default']
    'LazyParametresCategorie': typeof import("../components/parametres/Categorie.vue")['default']
    'LazyParametresDepartement': typeof import("../components/parametres/Departement.vue")['default']
    'LazyParametresMenu': typeof import("../components/parametres/Menu.vue")['default']
    'LazyParametresProfil': typeof import("../components/parametres/Profil.vue")['default']
    'LazyParametresService': typeof import("../components/parametres/Service.vue")['default']
    'LazyParametresUtilisateur': typeof import("../components/parametres/Utilisateur.vue")['default']
    'LazyParametresParametre': typeof import("../components/parametres/parametre.vue")['default']
    'LazyParametresUseData': typeof import("../components/parametres/useData")['default']
    'LazyTableauDetail': typeof import("../components/tableau/Detail.vue")['default']
    'LazyTableau': typeof import("../components/tableau/index.vue")['default']
    'LazyTableauT': typeof import("../components/tableau/t.vue")['default']
    'LazyTableauUtils': typeof import("../components/tableau/utils")['default']
    'LazyUtilityComingSoon': typeof import("../components/utility/comingSoon/index.vue")['default']
    'LazyUtilityMaintenance': typeof import("../components/utility/maintenance/index.vue")['default']
    'LazyVisiteur': typeof import("../components/visiteur/index.vue")['default']
    'LazyVueWebCam': typeof import("../components/vue-web-cam.vue")['default']
    'LazyContentDoc': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
    'LazyContentList': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
    'LazyContentNavigation': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
    'LazyContentQuery': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
    'LazyContentRenderer': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
    'LazyContentRendererMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
    'LazyContentSlot': typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
    'LazyDocumentDrivenEmpty': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
    'LazyDocumentDrivenNotFound': typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
    'LazyMarkdown': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
    'LazyProseCode': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
    'LazyProseCodeInline': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
    'LazyProsePre': typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
    'LazyProseA': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
    'LazyProseBlockquote': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
    'LazyProseEm': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
    'LazyProseH1': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
    'LazyProseH2': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
    'LazyProseH3': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
    'LazyProseH4': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
    'LazyProseH5': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
    'LazyProseH6': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
    'LazyProseHr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
    'LazyProseImg': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
    'LazyProseLi': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
    'LazyProseOl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
    'LazyProseP': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
    'LazyProseScript': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
    'LazyProseStrong': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
    'LazyProseTable': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
    'LazyProseTbody': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
    'LazyProseTd': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
    'LazyProseTh': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
    'LazyProseThead': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
    'LazyProseTr': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
    'LazyProseUl': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyMDC': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
    'LazyMDCRenderer': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
    'LazyMDCSlot': typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const PageHeader: typeof import("../components/global/PageHeader.vue")['default']
export const SiteHeader: typeof import("../components/global/SiteHeader.vue")['default']
export const WizarParametrageProfileInformationPersonnelle: typeof import("../components/WizarParametrageProfile/InformationPersonnelle.vue")['default']
export const WizarParametrageProfileInformationProfessionnelle: typeof import("../components/WizarParametrageProfile/InformationProfessionnelle.vue")['default']
export const AccountForgotPassword: typeof import("../components/account/ForgotPassword.vue")['default']
export const AccountLogin: typeof import("../components/account/Login.vue")['default']
export const AccountOtp: typeof import("../components/account/Otp.vue")['default']
export const AccountRegister: typeof import("../components/account/Register.vue")['default']
export const AccountResetPassword: typeof import("../components/account/ResetPassword.vue")['default']
export const Agenda: typeof import("../components/agenda/Agenda.vue")['default']
export const AgendaLocales: typeof import("../components/agenda/Locales")['default']
export const AgendaUtils: typeof import("../components/agenda/utils")['default']
export const AuthLockScreen: typeof import("../components/auth/LockScreen/index.vue")['default']
export const AuthLogin: typeof import("../components/auth/login/index.vue")['default']
export const AuthRecoverPassword: typeof import("../components/auth/recoverPassword/index.vue")['default']
export const AuthRegister: typeof import("../components/auth/register/index.vue")['default']
export const CommonCountToComponent: typeof import("../components/common/CountToComponent.vue")['default']
export const CommonRadioGroup: typeof import("../components/common/RadioGroup.vue")['default']
export const DashboardDashBoard: typeof import("../components/dashboard/DashBoard.vue")['default']
export const DashboardVisiteur: typeof import("../components/dashboard/Visiteur.vue")['default']
export const DashboardCommonDiagramme: typeof import("../components/dashboard/common/Diagramme.vue")['default']
export const DashboardCommonHistogramme: typeof import("../components/dashboard/common/Histogramme.vue")['default']
export const DashboardCommonStat: typeof import("../components/dashboard/common/Stat.vue")['default']
export const DashboardCommonTableauDeBord: typeof import("../components/dashboard/common/TableauDeBord.vue")['default']
export const DashboardCommonTendanceVisite: typeof import("../components/dashboard/common/TendanceVisite.vue")['default']
export const DashboardCommonData: typeof import("../components/dashboard/common/data")['default']
export const DashboardNotification: typeof import("../components/dashboard/notification.vue")['default']
export const DetailVisiteur: typeof import("../components/detail/Visiteur.vue")['default']
export const FormsAjouterProfil: typeof import("../components/forms/AjouterProfil.vue")['default']
export const FormsFormAgence: typeof import("../components/forms/FormAgence.vue")['default']
export const FormsFormCategorie: typeof import("../components/forms/FormCategorie.vue")['default']
export const FormsFormDepartement: typeof import("../components/forms/FormDepartement.vue")['default']
export const FormsFormMenu: typeof import("../components/forms/FormMenu.vue")['default']
export const FormsFormProfil: typeof import("../components/forms/FormProfil.vue")['default']
export const FormsFormService: typeof import("../components/forms/FormService.vue")['default']
export const FormsFormUser: typeof import("../components/forms/FormUser.vue")['default']
export const FormsNewPassword: typeof import("../components/forms/NewPassword.vue")['default']
export const FormsParametrageProfile: typeof import("../components/forms/ParametrageProfile.vue")['default']
export const FormsProfile: typeof import("../components/forms/Profile.vue")['default']
export const LayoutsCommonAppList: typeof import("../components/layouts/common/AppList.vue")['default']
export const LayoutsCommonAppSearch: typeof import("../components/layouts/common/AppSearch.vue")['default']
export const LayoutsCommonFooter: typeof import("../components/layouts/common/Footer.vue")['default']
export const LayoutsCommonHeaderLogo: typeof import("../components/layouts/common/HeaderLogo.vue")['default']
export const LayoutsCommonLanguageDropdown: typeof import("../components/layouts/common/LanguageDropdown.vue")['default']
export const LayoutsCommonMobileAppSearch: typeof import("../components/layouts/common/MobileAppSearch.vue")['default']
export const LayoutsCommonNotifications: typeof import("../components/layouts/common/Notifications.vue")['default']
export const LayoutsCommonParametre: typeof import("../components/layouts/common/Parametre.vue")['default']
export const LayoutsCommonParametreDropdown: typeof import("../components/layouts/common/ParametreDropdown.vue")['default']
export const LayoutsCommonProfile: typeof import("../components/layouts/common/Profile.vue")['default']
export const LayoutsCommonRightSideBar: typeof import("../components/layouts/common/RightSideBar.vue")['default']
export const LayoutsCommonSideBar: typeof import("../components/layouts/common/SideBar.vue")['default']
export const LayoutsCommonModalsModalDetail: typeof import("../components/layouts/common/modals/modalDetail.vue")['default']
export const LayoutsCommonStatStatatistique: typeof import("../components/layouts/common/stat/Statatistique.vue")['default']
export const LayoutsUtilsMenu: typeof import("../components/layouts/utils/menu")['default']
export const LayoutsUtilsRightSideBar: typeof import("../components/layouts/utils/rightSideBar")['default']
export const LayoutsUtilsTopBar: typeof import("../components/layouts/utils/topBar")['default']
export const LayoutsVerticalTopBar: typeof import("../components/layouts/vertical/TopBar.vue")['default']
export const LayoutsVerticalTopBarQrCode: typeof import("../components/layouts/vertical/TopBarQrCode.vue")['default']
export const LayoutsVertical: typeof import("../components/layouts/vertical/index.vue")['default']
export const ParametresAgence: typeof import("../components/parametres/Agence.vue")['default']
export const ParametresCategorie: typeof import("../components/parametres/Categorie.vue")['default']
export const ParametresDepartement: typeof import("../components/parametres/Departement.vue")['default']
export const ParametresMenu: typeof import("../components/parametres/Menu.vue")['default']
export const ParametresProfil: typeof import("../components/parametres/Profil.vue")['default']
export const ParametresService: typeof import("../components/parametres/Service.vue")['default']
export const ParametresUtilisateur: typeof import("../components/parametres/Utilisateur.vue")['default']
export const ParametresParametre: typeof import("../components/parametres/parametre.vue")['default']
export const ParametresUseData: typeof import("../components/parametres/useData")['default']
export const TableauDetail: typeof import("../components/tableau/Detail.vue")['default']
export const Tableau: typeof import("../components/tableau/index.vue")['default']
export const TableauT: typeof import("../components/tableau/t.vue")['default']
export const TableauUtils: typeof import("../components/tableau/utils")['default']
export const UtilityComingSoon: typeof import("../components/utility/comingSoon/index.vue")['default']
export const UtilityMaintenance: typeof import("../components/utility/maintenance/index.vue")['default']
export const Visiteur: typeof import("../components/visiteur/index.vue")['default']
export const VueWebCam: typeof import("../components/vue-web-cam.vue")['default']
export const ContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const ContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const ContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const ContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const ContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const ContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const ContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const DocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const DocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const Markdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const ProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const ProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const ProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const ProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const ProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const ProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const ProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const ProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const ProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const ProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const ProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const ProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const ProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const ProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const ProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const ProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const ProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const ProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const ProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const ProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const ProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const ProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const ProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const ProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const ProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const ProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const MDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const MDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const MDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyPageHeader: typeof import("../components/global/PageHeader.vue")['default']
export const LazySiteHeader: typeof import("../components/global/SiteHeader.vue")['default']
export const LazyWizarParametrageProfileInformationPersonnelle: typeof import("../components/WizarParametrageProfile/InformationPersonnelle.vue")['default']
export const LazyWizarParametrageProfileInformationProfessionnelle: typeof import("../components/WizarParametrageProfile/InformationProfessionnelle.vue")['default']
export const LazyAccountForgotPassword: typeof import("../components/account/ForgotPassword.vue")['default']
export const LazyAccountLogin: typeof import("../components/account/Login.vue")['default']
export const LazyAccountOtp: typeof import("../components/account/Otp.vue")['default']
export const LazyAccountRegister: typeof import("../components/account/Register.vue")['default']
export const LazyAccountResetPassword: typeof import("../components/account/ResetPassword.vue")['default']
export const LazyAgenda: typeof import("../components/agenda/Agenda.vue")['default']
export const LazyAgendaLocales: typeof import("../components/agenda/Locales")['default']
export const LazyAgendaUtils: typeof import("../components/agenda/utils")['default']
export const LazyAuthLockScreen: typeof import("../components/auth/LockScreen/index.vue")['default']
export const LazyAuthLogin: typeof import("../components/auth/login/index.vue")['default']
export const LazyAuthRecoverPassword: typeof import("../components/auth/recoverPassword/index.vue")['default']
export const LazyAuthRegister: typeof import("../components/auth/register/index.vue")['default']
export const LazyCommonCountToComponent: typeof import("../components/common/CountToComponent.vue")['default']
export const LazyCommonRadioGroup: typeof import("../components/common/RadioGroup.vue")['default']
export const LazyDashboardDashBoard: typeof import("../components/dashboard/DashBoard.vue")['default']
export const LazyDashboardVisiteur: typeof import("../components/dashboard/Visiteur.vue")['default']
export const LazyDashboardCommonDiagramme: typeof import("../components/dashboard/common/Diagramme.vue")['default']
export const LazyDashboardCommonHistogramme: typeof import("../components/dashboard/common/Histogramme.vue")['default']
export const LazyDashboardCommonStat: typeof import("../components/dashboard/common/Stat.vue")['default']
export const LazyDashboardCommonTableauDeBord: typeof import("../components/dashboard/common/TableauDeBord.vue")['default']
export const LazyDashboardCommonTendanceVisite: typeof import("../components/dashboard/common/TendanceVisite.vue")['default']
export const LazyDashboardCommonData: typeof import("../components/dashboard/common/data")['default']
export const LazyDashboardNotification: typeof import("../components/dashboard/notification.vue")['default']
export const LazyDetailVisiteur: typeof import("../components/detail/Visiteur.vue")['default']
export const LazyFormsAjouterProfil: typeof import("../components/forms/AjouterProfil.vue")['default']
export const LazyFormsFormAgence: typeof import("../components/forms/FormAgence.vue")['default']
export const LazyFormsFormCategorie: typeof import("../components/forms/FormCategorie.vue")['default']
export const LazyFormsFormDepartement: typeof import("../components/forms/FormDepartement.vue")['default']
export const LazyFormsFormMenu: typeof import("../components/forms/FormMenu.vue")['default']
export const LazyFormsFormProfil: typeof import("../components/forms/FormProfil.vue")['default']
export const LazyFormsFormService: typeof import("../components/forms/FormService.vue")['default']
export const LazyFormsFormUser: typeof import("../components/forms/FormUser.vue")['default']
export const LazyFormsNewPassword: typeof import("../components/forms/NewPassword.vue")['default']
export const LazyFormsParametrageProfile: typeof import("../components/forms/ParametrageProfile.vue")['default']
export const LazyFormsProfile: typeof import("../components/forms/Profile.vue")['default']
export const LazyLayoutsCommonAppList: typeof import("../components/layouts/common/AppList.vue")['default']
export const LazyLayoutsCommonAppSearch: typeof import("../components/layouts/common/AppSearch.vue")['default']
export const LazyLayoutsCommonFooter: typeof import("../components/layouts/common/Footer.vue")['default']
export const LazyLayoutsCommonHeaderLogo: typeof import("../components/layouts/common/HeaderLogo.vue")['default']
export const LazyLayoutsCommonLanguageDropdown: typeof import("../components/layouts/common/LanguageDropdown.vue")['default']
export const LazyLayoutsCommonMobileAppSearch: typeof import("../components/layouts/common/MobileAppSearch.vue")['default']
export const LazyLayoutsCommonNotifications: typeof import("../components/layouts/common/Notifications.vue")['default']
export const LazyLayoutsCommonParametre: typeof import("../components/layouts/common/Parametre.vue")['default']
export const LazyLayoutsCommonParametreDropdown: typeof import("../components/layouts/common/ParametreDropdown.vue")['default']
export const LazyLayoutsCommonProfile: typeof import("../components/layouts/common/Profile.vue")['default']
export const LazyLayoutsCommonRightSideBar: typeof import("../components/layouts/common/RightSideBar.vue")['default']
export const LazyLayoutsCommonSideBar: typeof import("../components/layouts/common/SideBar.vue")['default']
export const LazyLayoutsCommonModalsModalDetail: typeof import("../components/layouts/common/modals/modalDetail.vue")['default']
export const LazyLayoutsCommonStatStatatistique: typeof import("../components/layouts/common/stat/Statatistique.vue")['default']
export const LazyLayoutsUtilsMenu: typeof import("../components/layouts/utils/menu")['default']
export const LazyLayoutsUtilsRightSideBar: typeof import("../components/layouts/utils/rightSideBar")['default']
export const LazyLayoutsUtilsTopBar: typeof import("../components/layouts/utils/topBar")['default']
export const LazyLayoutsVerticalTopBar: typeof import("../components/layouts/vertical/TopBar.vue")['default']
export const LazyLayoutsVerticalTopBarQrCode: typeof import("../components/layouts/vertical/TopBarQrCode.vue")['default']
export const LazyLayoutsVertical: typeof import("../components/layouts/vertical/index.vue")['default']
export const LazyParametresAgence: typeof import("../components/parametres/Agence.vue")['default']
export const LazyParametresCategorie: typeof import("../components/parametres/Categorie.vue")['default']
export const LazyParametresDepartement: typeof import("../components/parametres/Departement.vue")['default']
export const LazyParametresMenu: typeof import("../components/parametres/Menu.vue")['default']
export const LazyParametresProfil: typeof import("../components/parametres/Profil.vue")['default']
export const LazyParametresService: typeof import("../components/parametres/Service.vue")['default']
export const LazyParametresUtilisateur: typeof import("../components/parametres/Utilisateur.vue")['default']
export const LazyParametresParametre: typeof import("../components/parametres/parametre.vue")['default']
export const LazyParametresUseData: typeof import("../components/parametres/useData")['default']
export const LazyTableauDetail: typeof import("../components/tableau/Detail.vue")['default']
export const LazyTableau: typeof import("../components/tableau/index.vue")['default']
export const LazyTableauT: typeof import("../components/tableau/t.vue")['default']
export const LazyTableauUtils: typeof import("../components/tableau/utils")['default']
export const LazyUtilityComingSoon: typeof import("../components/utility/comingSoon/index.vue")['default']
export const LazyUtilityMaintenance: typeof import("../components/utility/maintenance/index.vue")['default']
export const LazyVisiteur: typeof import("../components/visiteur/index.vue")['default']
export const LazyVueWebCam: typeof import("../components/vue-web-cam.vue")['default']
export const LazyContentDoc: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue")['default']
export const LazyContentList: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue")['default']
export const LazyContentNavigation: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue")['default']
export const LazyContentQuery: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue")['default']
export const LazyContentRenderer: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue")['default']
export const LazyContentRendererMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue")['default']
export const LazyContentSlot: typeof import("../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue")['default']
export const LazyDocumentDrivenEmpty: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue")['default']
export const LazyDocumentDrivenNotFound: typeof import("../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue")['default']
export const LazyMarkdown: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue")['default']
export const LazyProseCode: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue")['default']
export const LazyProseCodeInline: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue")['default']
export const LazyProsePre: typeof import("../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue")['default']
export const LazyProseA: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue")['default']
export const LazyProseBlockquote: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue")['default']
export const LazyProseEm: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue")['default']
export const LazyProseH1: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue")['default']
export const LazyProseH2: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue")['default']
export const LazyProseH3: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue")['default']
export const LazyProseH4: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue")['default']
export const LazyProseH5: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue")['default']
export const LazyProseH6: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue")['default']
export const LazyProseHr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue")['default']
export const LazyProseImg: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue")['default']
export const LazyProseLi: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue")['default']
export const LazyProseOl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue")['default']
export const LazyProseP: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue")['default']
export const LazyProseScript: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue")['default']
export const LazyProseStrong: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue")['default']
export const LazyProseTable: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue")['default']
export const LazyProseTbody: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue")['default']
export const LazyProseTd: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue")['default']
export const LazyProseTh: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue")['default']
export const LazyProseThead: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue")['default']
export const LazyProseTr: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue")['default']
export const LazyProseUl: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyMDC: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue")['default']
export const LazyMDCRenderer: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue")['default']
export const LazyMDCSlot: typeof import("../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
