// Generated by nuxi
<<<<<<< HEAD
=======
/// <reference types="@nuxt/content-edge" />
>>>>>>> cd3f1e3894792eeb7fd0c9dc292c9b4b75e3bd24
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxt/content-edge" />
/// <reference types="@nuxtjs/google-fonts" />
/// <reference types="nuxt-easy-lightbox" />
<<<<<<< HEAD
/// <reference types="@nuxt/telemetry" />
=======
>>>>>>> cd3f1e3894792eeb7fd0c9dc292c9b4b75e3bd24
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />
/// <reference types="nuxt" />
/// <reference path="types/app-defaults.d.ts" />
/// <reference path="types/plugins.d.ts" />
/// <reference path="types/build.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/app.config.d.ts" />
/// <reference types="vite/client" />
/// <reference path="types/content.d.ts" />
/// <reference types="@pinia/nuxt" />
/// <reference types="vue-router" />
/// <reference path="types/middleware.d.ts" />
/// <reference path="types/layouts.d.ts" />
/// <reference path="components.d.ts" />
/// <reference path="imports.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="schema/nuxt.schema.d.ts" />
/// <reference path="types/nitro.d.ts" />

export {}
